name: cmake

on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/cmake.yml"
      - "src/**"
      - "include/**"
      - "tests/**"
      - "CMakeLists.txt"
      - "pixi.toml"

  pull_request:
    branches: [main]
    paths:
      - ".github/workflows/cmake.yml"
      - "src/**"
      - "include/**"
      - "tests/**"
      - "CMakeLists.txt"
      - "pixi.toml"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2025, ubuntu-24.04, macos-15]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.9.3
        with:
          pixi-version: v0.61.0
          activate-environment: true
          cache: true

      - name: Configure (debug)
        run: cmake -S . -B build-cmake-debug -DCMAKE_BUILD_TYPE=Debug -DEVENTIDE_ENABLE_TEST=ON

      - name: Build (debug)
        if: runner.os != 'Windows'
        run: cmake --build build-cmake-debug

      - name: Build (debug, windows)
        if: runner.os == 'Windows'
        run: cmake --build build-cmake-debug --config Debug

      - name: Test (debug)
        if: runner.os != 'Windows'
        run: ./build-cmake-debug/unit_tests

      - name: Test (debug, windows)
        if: runner.os == 'Windows'
        run: .\build-cmake-debug\Debug\unit_tests.exe

      - name: Configure (release)
        run: cmake -S . -B build-cmake-release -DCMAKE_BUILD_TYPE=Release -DEVENTIDE_ENABLE_TEST=ON

      - name: Build (release)
        if: runner.os != 'Windows'
        run: cmake --build build-cmake-release

      - name: Build (release, windows)
        if: runner.os == 'Windows'
        run: cmake --build build-cmake-release --config Release

      - name: Test (release)
        if: runner.os != 'Windows'
        run: ./build-cmake-release/unit_tests

      - name: Test (release, windows)
        if: runner.os == 'Windows'
        run: .\build-cmake-release\Release\unit_tests.exe
