name: cmake

on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/cmake.yml"
      - "src/**"
      - "include/**"
      - "tests/**"
      - "CMakeLists.txt"
      - "pixi.toml"

  pull_request:
    branches: [main]
    paths:
      - ".github/workflows/cmake.yml"
      - "src/**"
      - "include/**"
      - "tests/**"
      - "CMakeLists.txt"
      - "pixi.toml"

jobs:
  build:
    name: ${{ matrix.os }} | async=ON | simdjson=ON
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2025, ubuntu-24.04, macos-15]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.9.3
        with:
          pixi-version: v0.61.0
          activate-environment: true
          cache: true

      - name: Configure
        run: >
          cmake -S . -B build-cmake
          -DCMAKE_BUILD_TYPE=Debug
          -DEVENTIDE_ENABLE_TEST=ON
          -DEVENTIDE_ENABLE_ASYNC=ON
          -DEVENTIDE_SERDE_ENABLE_SIMDJSON=ON

      - name: Build
        if: runner.os != 'Windows'
        run: cmake --build build-cmake

      - name: Build (windows)
        if: runner.os == 'Windows'
        run: cmake --build build-cmake --config Debug

      - name: Test
        if: runner.os != 'Windows'
        run: ./build-cmake/unit_tests

      - name: Test (windows)
        if: runner.os == 'Windows'
        run: .\build-cmake\Debug\unit_tests.exe
