name: xmake

on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/xmake.yml"
      - "src/**"
      - "include/**"
      - "tests/**"
      - "xmake.lua"
      - "pixi.toml"

  pull_request:
    branches: [main]
    paths:
      - ".github/workflows/xmake.yml"
      - "src/**"
      - "include/**"
      - "tests/**"
      - "xmake.lua"
      - "pixi.toml"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2025, ubuntu-24.04, macos-15]

    concurrency:
      group: ${{ github.ref }}-${{ github.base_ref }}-${{ github.head_ref }}-${{ matrix.os }}
      cancel-in-progress: false

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: "3.0.5"
          actions-cache-folder: ".xmake-cache"
          actions-cache-key: ${{ matrix.os }}
          package-cache: true
          package-cache-key: ${{ matrix.os }}

      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.9.3
        with:
          pixi-version: v0.61.0
          activate-environment: true
          cache: true
          locked: ${{ runner.os != 'Windows' }}

      - name: Build (debug)
        run: |
          pixi run ci-xmake-build debug

      - name: Build (release)
        run: |
          pixi run ci-xmake-build release
